version: '3'

networks:
  odoo_backend:
    name: odoo_backend
  frontend:
    name: frontend

services:
  odoo:
    image: toters/odoo:latest
    ports:
      - "8069:8069"
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    networks:
      - odoo_backend

  db:
    image: postgres:15
    container_name: postgres
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes: 
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    networks: 
      - odoo_backend
    restart: always

  odoo_runner_17:
    image: odoo_runner:17.0
    build:
      context: ./build/17.0
    container_name: odoo_runner_17
    environment:
      - ODOO_RC=/etc/odoo/odoo.conf
    networks:
      - odoo_backend
    volumes: 
      - ${ODOO_SRC}/odoo:/opt/odoo
      - ./conf/17.0:/etc/odoo
      - ${ODOO_DATA_PATH}/odoo17:/root/.local/share/Odoo
    ports:
      - 8069:8069
      - 8072:8072

