version: '3'

networks:
  odoo_backend:
    name: odoo_backend
  frontend:
    name: frontend

services:
  odoo:
    image: toters/odoo:latest
    ports:
      - "8069:8069"
    restart: always
    environment:
      POSTGRES_USER: "odoo"
      POSTGRES_PASSWORD: "odoo"
      POSTGRES_DB: "postgres"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - odoo_backend

  db:
    image: postgres:15
    container_name: postgres
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks: 
      - odoo_backend

 
