name: Deploy Odoo on Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install flake8, Bandit, and Safety
      run: |
        python -m pip install flake8 bandit 

    - name: Check Python code with flake8
      run: |
        flake8 --ignore=F401,W292,E501,W293,W291,W391
      continue-on-error: false

    - name: Check Python code with Bandit
      run: |
        bandit -r .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/17.0/Dockerfile
        push: true
        tags: toters/odoo:latest

    - name: Create report file
      run: echo "Placeholder content" > report.txt

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Add report file
        title: '[Example] Add report file'
        body: >
          This PR is auto-generated by 
          [create-pull-request](https://github.com/peter-evans/create-pull-request).
        labels: report, automated pr
